### ISSUE TITLE
[BUG] v2.0.11 breaks incident creation

### ISSUE THREAD

**Issue by initharrington** [incidentbot/incidentbot#613]
**Describe the bug**
The v2.0.11 deployment is broken when creating a new incident, it fails. Error in the pod:

```
[SQL: SELECT incidentrecord.additional_comms_channel, incidentrecord.additional_comms_channel_id, incidentrecord.additional_comms_channel_link, incidentrecord.boilerplate_message_ts, incidentrecord.channel_id, incidentrecord.channel_name, incidentrecord.components, incidentrecord.created_at, incidentrecord.description, incidentrecord.digest_message_ts, incidentrecord.has_private_channel, incidentrecord.id, incidentrecord.impact, incidentrecord.is_security_incident, incidentrecord.last_update_sent, incidentrecord.link, incidentrecord.meeting_link, incidentrecord.roles, incidentrecord.roles_all, incidentrecord.severity, incidentrecord.severities, incidentrecord.slug, incidentrecord.status, incidentrecord.statuses, incidentrecord.tags, incidentrecord.updated_at
FROM incidentrecord
WHERE incidentrecord.channel_id = %(channel_id_1)s OR incidentrecord.channel_name IS NULL OR incidentrecord.id IS NULL OR incidentrecord.slug IS NULL]
[parameters: {'channel_id_1': 'REMOVED'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-04 15:16:43 [error    ] incident lookup (single) query failed: (psycopg2.errors.UndefinedColumn) column incidentrecord.has_private_channel does not exist
LINE 1: ...rd.description, incidentrecord.digest_message_ts, incidentre...
```

**Version**
2.0.11

**To Reproduce**
1. /incidentbot
2. Create incident

**Expected behavior**
Incident is created

**Screenshots**
NA

**Environment (please complete the following information):**
k8s

**Additional context**
2.0.10 does not break

**Comment by initharrington** [comment]
I think I need to apply this:
https://github.com/incidentbot/incidentbot/blob/main/alembic/versions/c084a30ce811_add_cols_to_inc_record.py

**Comment by echoboomer** [comment]
Correct, you'll have to run the migration. I should've mentioned that in the release notes. This happens automatically if you're using the chart, which I assume you might not be. I'll have to come up with a better way to handle those cases.

**Comment by initharrington** [comment]
I am using the chart.  I have to sidecar my sqlproxy for auth and that doesn't work with the initContainer strategy (so I don't use it).  I am manually running a k8s job when I have to do a migration, which isn't great, but I haven't figured out a better solution yet.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: incident-bot-db-migration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: <REMOVED>
      containers:
      - name: db-migrations
        image: "eb129/incident-bot:util-v2.0.11"
        imagePullPolicy: Always
        args:
          - -c
          - alembic upgrade head
        command:
          - /bin/sh
        envFrom:
          - secretRef:
              name: incident-bot
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4-buster
        command:
          - <REMOVED>
        env:
          - name: <REMOVED>
            value: <REMOVED>
      restartPolicy: Never
```
