### ISSUE TITLE
[BUG] Statuspage incidents bug

### ISSUE THREAD

**Issue by antonioned** [incidentbot/incidentbot#680]
**Describe the bug**
We encountered a bug when updating/managing Statuspage incidents via Slack. We have the following config for this:

```
statuspage:
      enabled: true
      # The public URL of the Statuspage.
      url: https://example.statuspage.io
      permissions:
        groups:
          - devops
          - itops
```

I am part of the `devops` but not the `itops` slack group and with this config I keep getting an error in Slack, screenshot provided, even though I am able to update the Statuspage incident. As soon as I added myself to the `itops` group, I no longer get that error message.

**Version**
2.1.3

**To Reproduce**
1. Set up more than 1 slack group to manage Statuspage incidents.
2. Add user to only one of the groups.
3. Try managing the incident.

**Expected behavior**
User should not get a false-positive error message if is part of at least one slack group with permissions to manage Statuspage incidents.

**Screenshots**
![Image](https://github.com/user-attachments/assets/70d9dda7-7cc5-4f34-9002-64646a0b4b7a)

**Environment (please complete the following information):**
 - Platform: AWS EKS, Helm Chart
